---
# tasks file for ansible-nginx
- include: nginx-install.yml
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [installation, installation_nginx]

- include: nginx-rollback.yml
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [rollback, rollback_nginx]

- include: nginx-testing.yml
  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [testing, testing_nginx]
